OnlineExamSystem/urls.py
from django.contrib import admin
from django.urls import re_path as url
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

# 主路由
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('', include('front.urls')),
    # 没有这一句无法显示上传的图片
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

front/urls.py
from django.urls import path
from . import views

app_name = 'front'

urlpatterns = [
    path('', views.index, name='index'),
    path('stulogout/', views.stulogout, name='stulogout'),  # 学生退出登录
    path('tealogout/', views.tealogout, name='tealogout'),  # 学生退出登录
    path('studentLogin/', views.studentLogin, name='studentLogin'),  # 学生登录
    path('teacherLogin/', views.teacherLogin, name='teacherLogin'),  # 老师登录
    path('startExam/', views.startExam, name='startExam'),  # 开始考试
    path('calculateGrade/', views.calculateGrade, name='calculateGrade'),  # 交卷计算成绩
    path('showGrade/', views.showGrade, name='showGrade'),  # 成绩统计
]

reception/templates/stu/exam.html
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta http-equiv="content-type" content="text/html;charset=UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>在线答题考试系统</title>

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <script src="{% static 'js/jquery-1.11.3.min.js' %}"></script>
    <script src="{% static 'js/jquery.countdown.js' %}"></script>
    <!--时间js-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" />

    <link href="{% static 'css/test.css' %}" rel="stylesheet" type="text/css" />


</head>
<body>
<div class="main">
	<div class="test_main">
		<div class="nr_left">
			<div class="test">
            <nav class="navbar navbar-expand-sm bg-light navbar-light ">
                <ul class="navbar-nav">
                    <li class="nav-item active" style="text-align: center">
                        <a class="nav-link"><h3>当前科目:{{ subject }}</h3></a>
                    </li>
                    <li style="right: 140px; font-size: 30px;color: #000000;margin-left: 60px;margin-top: 15px">&nbsp;&nbsp;&nbsp;{{ title }}</li>
                    <li style="position:absolute;font-size: 30px;color: #9fcdff;margin-left: 80%;margin-top: 2%">{{ student.name }}</li>
                </ul>
            </nav>
				<form action="{% url 'front:calculateGrade' %}" method="post">
                <input type="hidden" name="sid" value="{{ student.sid }}">
                {# 获取当前考试科目#}
                <input type="hidden" name="subject" value="{{ subject }}">
					<div class="test_title">
						<font><input class="tijiao" type="submit" name="tijiao" value="交卷" style="text-align: center"></font>
					</div>
						<div class="test_content">
							<div class="test_content_title">
								<h2>单选题</h2>
                                <div id="timer" style="color:red"></div>
							</div>
						</div>
						<div class="test_content_nr">
							<ul>
                                {% for paper1 in paper %}
                                   {% for test in paper1.pid.all %}
                                       <li id="{{ forloop.counter }}">
                                        <div class="test_content_nr_tt">
											<i>{{ forloop.counter}}</i><span>({{ test.score }}分)</span>
                                            <font>{{ test.title | safe}}</font>

										</div>
                                       <div class="test_content_nr_main">
											<ul>
													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="A"/>
														<label>A.
                                                            <p class="ue" style="display: inline;">{{ test.a }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="B"/>
														<label>
															B.<p class="ue" style="display: inline;">{{ test.b }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="C"/>
														<label>
															C.<p class="ue" style="display: inline;">{{ test.c }}</p>
														</label>
													</li>

													<li class="option">
															<input type="radio" class="radioOrCheck" name="{{ test.id }}"
                                                            value="D"/>
														<label>
															D.<p class="ue" style="display: inline;">{{ test.d }}</p>
														</label>
													</li>
											</ul>
										</div>
                                        </li>
                                   {% endfor %}
                                {% endfor %}
							</ul>
						</div>
				</form>
			</div>
		</div>

	</div>
	<!--nr end-->
	<div class="foot"></div>
</div>
<SCRIPT type="text/javascript">
            var maxtime = {{ exam_time }}; //一个小时，按秒计算，自己调整!
            $(function () {
                timer = setInterval("CountDown()", 1000);
            })
                function CountDown() {
                    if (maxtime >= 0) {
                        minutes = Math.floor(maxtime / 60);
                        seconds = Math.floor(maxtime % 60);
                        msg = "距离考试结束还有" + minutes + "分" + seconds + "秒";
                        {#document.all["timer"].innerHTML = msg;#}
                        document.getElementById('timer').innerHTML = msg;
                        if (maxtime == 5 * 60)alert("还剩5分钟");
                            --maxtime;
                    } else{
                        {#clearInterval(timer);#}
                        {#alert("时间到，结束!");#}
                        document.getElementsByClassName('tijiao').click();
                    }
                }

</SCRIPT>
<div id="warring" style="color:red"></div>
</body>
</html>

reception/templates/stu/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="icon"
          href="https://edu-image.nosdn.127.net/32a8dd2a-b9aa-4ec9-abd5-66cd8751befb.png?imageView&quality=100">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- 必须在引入bootstarp.js之前引入 -->
    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>

    <script src="{% static 'bootstrap-4.3.1-dist/js/bootstrap.min.js' %}"></script>

    <title>首页</title>

</head>
<body>


<div class="container">
<nav class="navbar navbar-expand-sm bg-light navbar-light ">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="/"><h3>欢迎来到，智能组卷在线考试系统</h3></a>
        </li>
    </ul>
    <ul class="navbar-nav center">
        <li style="left: 20px">
            <button data-target="#stuModal" data-toggle="modal" class="btn btn-primary">学生登陆</button>
        </li>
        &nbsp;&nbsp;&nbsp;
        <li style="left: 100px">
            <button data-target="#teaModal" data-toggle="modal" class="btn btn-primary">教师登陆</button>
        </li>
        &nbsp;&nbsp;&nbsp;
        <li class="nav-item">
            <a class="nav-link" href="/admin">管理员登录</a>
        </li>

        <li style="position:absolute;right:10%;font-size: 35px;color: orange">{{ message }}{{ student.name }}</li>

        <li style="position:absolute;right:3%;top:25%">
             <a href="{% url 'front:stulogout' %}"><button data-target="#myModal" data-toggle="modal" class="btn btn-primary">退出</button></a>
        </li>
    </ul>
</nav>

    <br>
    <ul class="nav nav-pills" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" data-toggle="pill" href="#home">个人信息</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#menu1">考试信息</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" data-toggle="pill" href="#menu2">成绩查询</a>
        </li>
    </ul>

    <div class="tab-content">
        <div id="home" class="container tab-pane active"><br>
            <h3>登录确认个人信息</h3>
            <table class="table">
                <thead>
                <tr>
                    <th>项目</th>
                    <th class="left">个人信息</th>
                </tr>
                </thead>
                <tbody>
                <tr class="table-success">
                    <td>学号</td>
                    <td>{{ student.sid }}</td>
                </tr>
                <tr class="table-primary">
                    <td>姓名</td>
                    <td>{{ student.name }}</td>
                </tr>
                <tr class="table-success">
                    <td>性别</td>
                    {% if student.sex == 1 %}
                        <td>男</td>
                    {% elif student.sex == 0 %}
                        <td>女</td>
                    {% else %}
                        <td> </td>
                    {% endif %}
                </tr>

                </tr>
                <tr class="table-active">
                    <td>年龄</td>
                    <td>{{ student.age }}</td>
                </tr>

                <tr class="table-danger">
                    <td>学院</td>
                    <td>{{ student.xueyuan.name }}</td>
                </tr>

                <tr class="table-success">
                    <td>专业</td>
                    <td>{{ student.major.zhuanye }}</td>
                </tr>

                <tr class="table-warning">
                    <td>邮箱地址</td>
                    <td>{{ student.email }}</td>
                </tbody>
            </table>
        </div>

        <div id="menu1" class="container tab-pane fade"><br>
            <h3>考试信息</h3>
            <p></p>
            <table class="table">
                <thead>
                <tr>
                    <th>学号</th>
                    <th>姓名</th>
                    <th>试题</th>
                    <th>考试科目</th>
                    <th>考试时间</th>
                    <th>状态</th>
                </tr>
                </thead>
                <tbody>
                {#   遍历字典  paper #}
                {% for paper1 in paper %}
                    <tr class="table-info">
                        <td>{{ student.sid }}</td>
                        <td>{{ student.name }}</td>
                        <td>{{ paper1.title }}</td>
                        <td>{{ paper1.course.course_name }}</td>
                        <td>{{ paper1.examtime }}</td>
                        <td>
                            <a href="{% url 'front:startExam' %}?sid={{ student.sid }}&title={{ paper1.title }}&subject={{ paper1.course.course_name }}">
                                <button class="btn btn-primary startTest" id="toExam+{{ paper1.course.course_name }}">开始考试</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>

        <div id="menu2" class="container tab-pane fade"><br>
            <h3>考试成绩</h3>
            <p></p>
            <table class="table">
                <thead>
                <tr>
                    <th>姓名</th>
                    <th>科目</th>
                    <th>成绩</th>

                </tr>
                </thead>
                <tbody>

                {% for grade1 in grade %}
                    <tr class="table-primary">
                        <td>{{ grade1.xuehao }}</td>
                        <td>{{ grade1.course }}</td>
                        <td>{{ grade1.grade }}</td>

                    </tr>
                {% endfor %}


                </tbody>
            </table>
        </div>
    </div>
</div>


{#学生登录的模态对话框#}
<div class="modal fade" tabindex="-1" role="dialog" id="stuModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">学生登陆</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>

            </div>
            <form class="form-horizontal" action="{% url 'front:studentLogin' %}" method="post">
                {% csrf_token %}
                <div class="modal-body">

                    <div class="form-group">
                        <label class="col-sm-3 control-label">学生学号</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="id" placeholder="输入学号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-9">
                            <input type="password" class="form-control" name="password" placeholder="输入密码">
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">登陆</button>
                </div>
            </form>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div>

{#老师登录的模态对话框#}
<div class="modal fade" tabindex="-1" role="dialog" id="teaModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">教师登陆</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form class="form-horizontal" action="{% url 'front:teacherLogin' %}" method="post">
                <div class="modal-body">

                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-3 control-label">教师工号</label>
                        <div class="col-sm-9">
                            <input type="text" class="form-control" name="id" placeholder="输入学号">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="addr" class="col-sm-3 control-label">密码</label>
                        <div class="col-sm-9">
                            <input type="password" name="password" placeholder="输入密码" class="form-control">
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="submit" class="btn btn-primary">登陆</button>
                </div>
            </form>
        </div>
    </div>
</div>

</body>

<script>
    $("#toExam+{{ paper1.course }}").click(function () {

    });

    var startTest = document.getElementsByClassName('startTest')
    // console.log(startTest[0])
    startTest[0].onclick = function () {
        // startTest[0].style.display = 'none'
        // startTest[0].remove()
        // var newDiv = document.createElement('button')
        // console.log(newDiv)
        startTest[0].innerHTML = '已开始'
        window.history.back()

    }

</script>
</html>